# Generated by Django 6.0.4 on 2026-05-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='expected_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='logentry',
            name='custom_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
