# Generated by Django 6.0.4 on 2026-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_behavior_expected_metrics_logentry_custom_metrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ['-date']},
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['behavior', '-date'], name='behavior_date_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['-date'], name='date_only_idx'),
        ),
    ]
