# Generated by Django 6.0.4 on 2026-05-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_logentry_options_logentry_behavior_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
