# Generated by Django 6.0.4 on 2026-05-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_behavior_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='special_note',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
