# Generated by Django 6.0.4 on 2026-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_logentry_special_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
